spring:
  application:
    name: ad-filters-subscriber
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 6 #警告阈值, 原始规则长度小于该值时会输出警告日志

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:
      - name: AdGuard 基础过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt
        type: easylist

      - name: AdGuard 移动广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt
        type: easylist

      - name: AdGuard 防跟踪保护过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt
        type: easylist

      - name: AdGuard URL跟踪过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt
        type: easylist

      - name: AdGuard 恼人广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
        type: easylist

      - name: AdGuard 解除搜索广告和自我推销过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_10_Useful/filter.txt
        type: easylist

      - name: AdGuard 中文过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt
        type: easylist

      - name: 大圣净化
        path: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
        type: hosts

      - name: AWAvenue-Adblock-Rule
        path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
        type: easylist

      - name: NoAppDownload
        path: https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt
        type: easylist

      - name: Cats-Team AdBlock List Lite
        path: https://raw.githubusercontent.com/Cats-Team/AdRules/main/adblock_lite.txt
        type: easylist

      - name: 1Hosts (Lite)
        path: https://o0.pages.dev/Lite/adblock.txt
        type: easylist

      - name: hagezi/dns-blocklists pro
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/multi.txt
        type: easylist

    #本地规则文件
    local:
      - name: 'xndeye private adblock list'
        path: 'rule/private.txt' #支持绝对/相对路径
        type: easylist

  #输出配置
  output:
    #文件头配置，将自动作为注释添加至每个规则文件开始
    #可使用占位符 ${name}、${type}、${desc} 以及 ${date} (当前日期)
    file_header: |
      xndeye adblock list for ${type}
      Last Modified: ${date}
      Homepage: https://github.com/xndeye/adblock_list/tree/beta

    path: rule #输出规则文件的路径，支持绝对/相对路径
    #输出规则文件列表 （！注意缩进，且每个类型只能输出一个文件）
    files:
      - name: easylist.txt     #必要参数: 文件名
        type: easylist         #必要参数: 文件类型: easylist、dnsmasq、clash、smartdns、hosts
        filter:
          - basic              #基本规则，不包含任何控制、匹配符号, 可以转换为 hosts
          - wildcard           #通配规则，仅使用通配符
          - unknown            #其他规则，如使用了正则、高级修饰符号等，这表示目前无法支持

      - name: dns.txt
        type: easylist
        filter:
          - basic
          - wildcard

      - name: dnsmasq.conf
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.conf
        type: smartdns

      - name: hosts
        type: hosts
